Repository TeamTheGenius/GitGet_Server, pull requests merged in 2024-05, with the labels that each got.

#181 [FEAT] AWS S3 파일 저장 이슈 해결
  .github/workflows/main.yml
  src/main/java/com/genius/gitget/challenge/myChallenge/controller/MyChallengeController.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 !HOTFIX

#182 [CHORE] main yml 수정
  .github/workflows/main.yml
Labels: 🧑🏻‍💻 BE, 🔧 !HOTFIX

#184 [FEAT] nginx & docker-compose 무중단 배포
  .github/workflows/main.yml
  Dockerfile
  appspec.yml
  scripts/health.sh
  src/main/java/com/genius/gitget/global/security/config/SecurityConfig.java
Labels: 💡feature, 🧑🏻‍💻 BE

#183 [REFACTOR] 파일이 저장소에 존재하지 않을 때에 대한 응답 데이터 리팩토링 및 추가 예외 처리
  src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
  src/main/java/com/genius/gitget/global/file/service/FileManager.java
  src/main/java/com/genius/gitget/global/file/service/FileUtil.java
  src/main/java/com/genius/gitget/global/file/service/LocalFileManager.java
  src/main/java/com/genius/gitget/global/file/service/S3FileManager.java
  src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
  src/test/java/com/genius/gitget/global/file/service/FileUtilTest.java
Labels: 💡feature, ⚙️ refactor, 🧑🏻‍💻 BE

#186 [FEAT] Slack Webhook 적용
  .github/workflows/main.yml
Labels: 💡feature, 🧑🏻‍💻 BE

#187 [FIX] 추천 챌린지가 제대로 전달되지 않는 버그 픽스
  src/main/java/com/genius/gitget/challenge/instance/repository/InstanceRepository.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceHomeService.java
  src/test/java/com/genius/gitget/challenge/home/service/InstanceHomeServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/repository/InstanceRepositoryTest.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 !HOTFIX

#189 [FIX] FE에서 Item을 식별하는 코드가 제대로 설정되지 않는 버그 픽스
  src/main/java/com/genius/gitget/store/item/controller/ItemController.java
  src/main/java/com/genius/gitget/store/item/domain/Item.java
  src/main/java/com/genius/gitget/store/item/dto/ItemResponse.java
  src/main/java/com/genius/gitget/store/item/repository/ItemRepository.java
  src/main/java/com/genius/gitget/store/item/service/ItemProvider.java
  src/main/resources/data.sql
  src/test/java/com/genius/gitget/challenge/item/service/ItemProviderTest.java
  src/test/java/com/genius/gitget/challenge/item/service/ItemServiceTest.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 fix
