Repository TeamTheGenius/GitGet_Server, pull requests merged in 2024-07, with the labels that each got.

#214 [FEAT] 예외 발생 시, Slack 채널에 메세지를 보내는 기능 추가
  build.gradle
  src/main/java/com/genius/gitget/challenge/certification/util/DateUtil.java
  src/main/java/com/genius/gitget/global/util/exception/handler/BusinessExceptionHandler.java
  src/main/java/com/genius/gitget/global/util/exception/handler/FileExceptionHandler.java
  src/main/java/com/genius/gitget/global/util/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/genius/gitget/global/util/exception/handler/MessageSender.java
  src/main/java/com/genius/gitget/slack/service/SlackMessageUtil.java
  src/main/java/com/genius/gitget/slack/service/SlackService.java
  src/main/java/com/genius/gitget/slack/service/SlackServiceImpl.java
  src/main/resources/static/favicon.ico
Labels: 🧑🏻‍💻 BE, 🖥️ server

#219 2차 배포 (기능 추가 및 버그 픽스)
  README.md
  build.gradle
  src/main/java/com/genius/gitget/challenge/certification/controller/CertificationController.java
  src/main/java/com/genius/gitget/challenge/certification/controller/GithubController.java
  src/main/java/com/genius/gitget/challenge/certification/service/GithubProvider.java
  src/main/java/com/genius/gitget/challenge/certification/util/DateUtil.java
  src/main/java/com/genius/gitget/challenge/instance/controller/InstanceController.java
  src/main/java/com/genius/gitget/challenge/instance/controller/InstanceDetailController.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
  src/main/java/com/genius/gitget/challenge/instance/dto/detail/InstanceResponse.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceDetailService.java
  src/main/java/com/genius/gitget/challenge/myChallenge/controller/MyChallengeController.java
  src/main/java/com/genius/gitget/challenge/participant/service/ParticipantProvider.java
  src/main/java/com/genius/gitget/global/util/exception/handler/BusinessExceptionHandler.java
  src/main/java/com/genius/gitget/global/util/exception/handler/FileExceptionHandler.java
  src/main/java/com/genius/gitget/global/util/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/genius/gitget/global/util/exception/handler/MessageSender.java
  src/main/java/com/genius/gitget/profile/service/ProfileService.java
  src/main/java/com/genius/gitget/schedule/controller/ProgressController.java
  src/main/java/com/genius/gitget/schedule/service/ProgressService.java
  src/main/java/com/genius/gitget/schedule/service/ScheduleService.java
  src/main/java/com/genius/gitget/slack/service/SlackMessageUtil.java
  src/main/java/com/genius/gitget/slack/service/SlackService.java
  src/main/java/com/genius/gitget/slack/service/SlackServiceImpl.java
  src/main/java/com/genius/gitget/store/item/controller/ItemController.java
  src/main/resources/static/favicon.ico
  src/test/java/com/genius/gitget/challenge/certification/util/DateUtilTest.java
  src/test/java/com/genius/gitget/challenge/instance/service/ProgressServiceTest.java
Labels: 🧑🏻‍💻 BE, 🖥️ server

#218 [FEAT] facade pattern - Topic
  src/main/java/com/genius/gitget/admin/topic/dto/TopicUpdateRequest.java
  src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
  src/main/java/com/genius/gitget/global/file/service/FileHolderFinder.java
  src/main/java/com/genius/gitget/profile/service/ProfileService.java
  src/main/java/com/genius/gitget/signout/Signout.java
  src/main/java/com/genius/gitget/signout/SignoutRepository.java
  src/main/java/com/genius/gitget/topic/controller/TopicController.java
  src/main/java/com/genius/gitget/topic/domain/Topic.java
  src/main/java/com/genius/gitget/topic/dto/TopicCreateRequest.java
  src/main/java/com/genius/gitget/topic/dto/TopicDetailResponse.java
  src/main/java/com/genius/gitget/topic/dto/TopicIndexResponse.java
  src/main/java/com/genius/gitget/topic/dto/TopicPagingResponse.java
  src/main/java/com/genius/gitget/topic/dto/TopicUpdateRequest.java
  src/main/java/com/genius/gitget/topic/repository/TopicRepository.java
  src/main/java/com/genius/gitget/topic/service/TopicService.java
  src/main/java/com/genius/gitget/topic/serviceFacade/TopicFacade.java
  src/main/java/com/genius/gitget/topic/serviceFacade/TopicFacadeImpl.java
  src/test/java/com/genius/gitget/admin/topic/controller/TopicControllerTest.java
  src/test/java/com/genius/gitget/admin/topic/repository/TopicRepositoryTest.java
  src/test/java/com/genius/gitget/admin/topic/service/TopicFacadeTest.java
  src/test/java/com/genius/gitget/admin/topic/service/TopicServiceTest.java
  src/test/java/com/genius/gitget/challenge/home/controller/InstanceHomeControllerTest.java
  src/test/java/com/genius/gitget/challenge/home/service/InstanceHomeServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/controller/InstanceControllerTest.java
  src/test/java/com/genius/gitget/challenge/instance/repository/InstanceSearchRepositoryTest.java
  src/test/java/com/genius/gitget/challenge/instance/service/InstanceSearchServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/service/InstanceServiceTest.java
  src/test/java/com/genius/gitget/challenge/likes/LikesTest.java
  src/test/java/com/genius/gitget/challenge/likes/controller/LikesControllerTest.java
  src/test/java/com/genius/gitget/challenge/likes/service/LikesServiceTest.java
  src/test/java/com/genius/gitget/payment/controller/PaymentControllerTest.java
  src/test/java/com/genius/gitget/payment/service/PaymentServiceTest.java
  src/test/java/com/genius/gitget/profile/controller/ProfileControllerTest.java
  src/test/java/com/genius/gitget/profile/service/ProfileServiceTest.java
Labels: ⚙️ refactor, 🧑🏻‍💻 BE

#223 [REFACTOR] JWT 처리 방식 변경 및 리팩토링
  src/main/java/com/genius/gitget/challenge/user/domain/User.java
  src/main/java/com/genius/gitget/global/security/config/CustomCorsConfigurationSource.java
  src/main/java/com/genius/gitget/global/security/config/SecurityConfig.java
  src/main/java/com/genius/gitget/global/security/constants/JwtRule.java
  src/main/java/com/genius/gitget/global/security/controller/AuthController.java
  src/main/java/com/genius/gitget/global/security/dto/TokenRequest.java
  src/main/java/com/genius/gitget/global/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/genius/gitget/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/genius/gitget/global/security/service/CustomUserDetailsService.java
  src/main/java/com/genius/gitget/global/security/service/JwtFacade.java
  src/main/java/com/genius/gitget/global/security/service/JwtFacadeService.java
  src/main/java/com/genius/gitget/global/security/service/JwtGenerator.java
  src/main/java/com/genius/gitget/global/security/service/JwtUtil.java
  src/main/java/com/genius/gitget/global/security/service/TokenService.java
  src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
  src/test/java/com/genius/gitget/admin/topic/controller/TopicControllerTest.java
  src/test/java/com/genius/gitget/challenge/certification/controller/CertificationControllerTest.java
  src/test/java/com/genius/gitget/challenge/home/controller/InstanceHomeControllerTest.java
  src/test/java/com/genius/gitget/challenge/instance/controller/InstanceControllerTest.java
  src/test/java/com/genius/gitget/challenge/likes/controller/LikesControllerTest.java
  src/test/java/com/genius/gitget/global/security/config/SecurityConfigTest.java
  src/test/java/com/genius/gitget/global/security/service/JwtFacadeServiceTest.java
  src/test/java/com/genius/gitget/global/security/service/JwtServiceTest.java
  src/test/java/com/genius/gitget/global/security/service/JwtUtilTest.java
  src/test/java/com/genius/gitget/global/security/service/TokenServiceTest.java
  src/test/java/com/genius/gitget/payment/controller/PaymentControllerTest.java
  src/test/java/com/genius/gitget/profile/controller/ProfileControllerTest.java
  src/test/java/com/genius/gitget/util/TokenTestUtil.java
Labels: ⚙️ refactor, 🧑🏻‍💻 BE

#230 [FIX] 실패한 챌린지 경우 마이챌린지의 완료 탭에 나타나지 않는 버그 픽스
  src/main/java/com/genius/gitget/challenge/myChallenge/service/MyChallengeService.java
  src/main/java/com/genius/gitget/challenge/participant/repository/ParticipantRepository.java
  src/main/java/com/genius/gitget/challenge/participant/service/ParticipantProvider.java
  src/test/java/com/genius/gitget/challenge/participant/service/ParticipantProviderTest.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 fix

#226 [FEAT] instanceController, instanceHomeController 리펙토링
  src/main/java/com/genius/gitget/challenge/instance/controller/InstanceController.java
  src/main/java/com/genius/gitget/challenge/instance/controller/InstanceHomeController.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceCreateRequest.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceDetailResponse.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstancePagingResponse.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceUpdateDTO.java
  src/main/java/com/genius/gitget/challenge/instance/facade/InstanceFacade.java
  src/main/java/com/genius/gitget/challenge/instance/facade/InstanceFacadeService.java
  src/main/java/com/genius/gitget/challenge/instance/facade/InstanceHomeFacade.java
  src/main/java/com/genius/gitget/challenge/instance/facade/InstanceHomeFacadeService.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceHomeService.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceRecommendationService.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceSearchService.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
  src/main/java/com/genius/gitget/topic/controller/TopicController.java
  src/main/java/com/genius/gitget/topic/facade/TopicFacade.java
  src/main/java/com/genius/gitget/topic/facade/TopicFacadeService.java
  src/test/java/com/genius/gitget/challenge/home/service/ChallengeRecommendationServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/repository/InstanceSearchRepositoryTest.java
  src/test/java/com/genius/gitget/challenge/instance/service/InstanceFacadeTest.java
  src/test/java/com/genius/gitget/challenge/instance/service/InstanceHomeFacadeTest.java
  src/test/java/com/genius/gitget/challenge/instance/service/InstanceSearchServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/service/InstanceServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/util/TestDTOFactory.java
  src/test/java/com/genius/gitget/challenge/instance/util/TestSetup.java
  src/test/java/com/genius/gitget/topic/controller/TopicControllerTest.java
  src/test/java/com/genius/gitget/topic/repository/TopicRepositoryTest.java
  src/test/java/com/genius/gitget/topic/service/TopicFacadeTest.java
Labels: 📚 documentation, 💡feature, ⚙️ refactor, 🧑🏻‍💻 BE, 🖥️ server, 🎮 test

#231 [FEAT] LikesController Facade & DCI 패턴 도입
  src/main/java/com/genius/gitget/challenge/likes/controller/LikesController.java
  src/main/java/com/genius/gitget/challenge/likes/domain/Likes.java
  src/main/java/com/genius/gitget/challenge/likes/facade/LikesFacade.java
  src/main/java/com/genius/gitget/challenge/likes/facade/LikesFacadeService.java
  src/main/java/com/genius/gitget/challenge/likes/service/LikesService.java
  src/test/java/com/genius/gitget/challenge/instance/service/InstanceDetailServiceTest.java
  src/test/java/com/genius/gitget/challenge/likes/controller/LikesControllerTest.java
  src/test/java/com/genius/gitget/challenge/likes/service/LikesFacadeTest.java
  src/test/java/com/genius/gitget/challenge/likes/service/LikesServiceTest.java
Labels: 💡feature, ⚙️ refactor, 🧑🏻‍💻 BE, 🖥️ server, 🎮 test

#232 [FIX] 실패한 챌린지에 대해 달성율이 나오지 않는 버그 픽스
  src/main/java/com/genius/gitget/challenge/myChallenge/dto/DoneResponse.java
  src/main/java/com/genius/gitget/challenge/myChallenge/service/MyChallengeService.java
  src/test/java/com/genius/gitget/challenge/myChallenge/service/MyChallengeServiceTest.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 fix
