Repository TeamTheGenius/GitGet_Server, pull requests merged in 2024-02, with the labels that each got.

#56 [HOTFIX] Instance entity 이름 변경
  src/main/java/com/genius/gitget/challenge/home/dto/HomeInstanceResponse.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
  src/main/java/com/genius/gitget/challenge/instance/dto/search/InstanceSearchResponse.java
  src/test/java/com/genius/gitget/challenge/home/controller/HomeControllerTest.java
  src/test/java/com/genius/gitget/challenge/home/service/HomeServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/repository/InstanceRepositoryTest.java
Labels: 🧑🏻‍💻 BE

#61 [FEAT] 어드민 페이지 파일 api 적용
  src/main/java/com/genius/gitget/admin/topic/controller/TopicController.java
  src/main/java/com/genius/gitget/admin/topic/domain/Topic.java
  src/main/java/com/genius/gitget/admin/topic/dto/TopicCreateRequest.java
  src/main/java/com/genius/gitget/admin/topic/dto/TopicDetailResponse.java
  src/main/java/com/genius/gitget/admin/topic/dto/TopicPagingResponse.java
  src/main/java/com/genius/gitget/admin/topic/dto/TopicUpdateRequest.java
  src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
  src/main/java/com/genius/gitget/challenge/config/WebConfig.java
  src/main/java/com/genius/gitget/challenge/home/service/HomeService.java
  src/main/java/com/genius/gitget/challenge/instance/controller/InstanceController.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceCreateRequest.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceDetailResponse.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstancePagingResponse.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceUpdateRequest.java
  src/main/java/com/genius/gitget/challenge/instance/dto/search/InstanceSearchResponse.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceSearchService.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
  src/main/java/com/genius/gitget/challenge/instance/service/StringToEnum.java
  src/main/java/com/genius/gitget/global/file/dto/FileRequest.java
  src/test/java/com/genius/gitget/admin/topic/repository/TopicRepositoryTest.java
Labels: 💡feature, 🧑🏻‍💻 BE

#60 [HOTFIX] JWT Filter에서 예외 발생 시 처리하지 못하는 로직 수정
  src/main/java/com/genius/gitget/global/security/config/SecurityConfig.java
  src/main/java/com/genius/gitget/global/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/genius/gitget/global/security/handler/OAuth2SuccessHandler.java
  src/test/java/com/genius/gitget/global/security/config/SecurityConfigTest.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 !HOTFIX

#62 [FEAT] 토픽 삭제 예외 기능 추가
  src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
  src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
  src/test/java/com/genius/gitget/admin/topic/controller/TopicControllerTest.java
Labels: 💡feature, 🔧 !HOTFIX

#64 [FEAT] Files 엔티티 연관관계에 대해 영속성 전이 설정
  src/main/java/com/genius/gitget/admin/topic/domain/Topic.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
  src/main/java/com/genius/gitget/challenge/user/domain/User.java
Labels: 💡feature, 🧑🏻‍💻 BE

#65 [FEAT] 동적쿼리를 적용한 검색 기능 개발
  build.gradle
  src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
  src/main/java/com/genius/gitget/challenge/home/controller/HomeController.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Progress.java
  src/main/java/com/genius/gitget/challenge/instance/dto/search/InstanceSearchResponse.java
  src/main/java/com/genius/gitget/challenge/instance/repository/SearchRepository.java
  src/main/java/com/genius/gitget/challenge/instance/repository/SearchRepositoryCustom.java
  src/main/java/com/genius/gitget/challenge/instance/repository/SearchRepositoryImpl.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceSearchService.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
  src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
  src/test/java/com/genius/gitget/admin/topic/controller/TopicControllerTest.java
  src/test/java/com/genius/gitget/admin/topic/service/TopicServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/repository/InstanceSearchRepositoryTest.java
  src/test/java/com/genius/gitget/challenge/instance/service/InstanceSearchServiceTest.java
  src/test/java/com/genius/gitget/querydsl/QuerydslBasicTest.java
  src/test/java/com/genius/gitget/util/file/FileTestUtil.java
Labels: 💡feature, 🧑🏻‍💻 BE

#67 [BUG] Topic 삭제 요청 시, 삭제가 되지 않는 버그
  src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
  src/main/java/com/genius/gitget/challenge/instance/controller/InstanceController.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceDetailResponse.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
  src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
  src/main/java/com/genius/gitget/global/file/service/FileUtil.java
  src/main/java/com/genius/gitget/global/file/service/FilesService.java
  src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
  src/test/java/com/genius/gitget/global/file/service/FileUtilTest.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 !HOTFIX

#72 [BUG] 인스턴스 수정 시, 수정이 되지 않는 버그
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstancePagingResponse.java
  src/main/java/com/genius/gitget/global/file/service/FilesService.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 !HOTFIX

#75 [FEAT] 어드민 API 접근 권한 설정
  src/main/java/com/genius/gitget/global/security/config/SecurityConfig.java
  src/test/java/com/genius/gitget/global/security/config/SecurityConfigTest.java
  src/test/java/com/genius/gitget/util/WithMockCustomUserSecurityContextFactory.java
Labels: 💡feature, 🧑🏻‍💻 BE

#89 [FEAT] Item 관련 Entity 및 Repository 작성
  src/main/java/com/genius/gitget/challenge/item/domain/Item.java
  src/main/java/com/genius/gitget/challenge/item/domain/ItemCategory.java
  src/main/java/com/genius/gitget/challenge/item/domain/UserItem.java
  src/main/java/com/genius/gitget/challenge/item/repository/ItemRepository.java
  src/main/java/com/genius/gitget/challenge/item/repository/UserItemRepository.java
  src/main/java/com/genius/gitget/challenge/user/domain/User.java
Labels: 💡feature, 🧑🏻‍💻 BE
