Repository TeamTheGenius/GitGet_Server, pull requests merged in 2024-04, with the labels that each got.

#151 [REFACTOR] CertificationService의 전체/주간인증 조회 로직 개선
  src/main/java/com/genius/gitget/challenge/certification/controller/CertificationController.java
  src/main/java/com/genius/gitget/challenge/certification/dto/WeekResponse.java
  src/main/java/com/genius/gitget/challenge/certification/service/CertificationService.java
  src/main/java/com/genius/gitget/challenge/user/dto/UserProfileInfo.java
  src/main/java/com/genius/gitget/challenge/user/service/UserService.java
  src/main/java/com/genius/gitget/global/security/controller/AuthController.java
  src/test/java/com/genius/gitget/challenge/certification/service/CertificationServiceTest.java
  src/test/java/com/genius/gitget/challenge/user/service/UserServiceTest.java
Labels: ⚙️ refactor, 🧑🏻‍💻 BE

#158 [BUILD] AWS 배포 자동화 적용
  .github/workflows/main.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/genius/gitget/challenge/user/domain/User.java
  src/main/java/com/genius/gitget/global/security/config/CustomCorsConfigurationSource.java
  src/main/java/com/genius/gitget/global/security/controller/AuthController.java
  src/main/java/com/genius/gitget/global/security/handler/OAuth2FailureHandler.java
  src/main/java/com/genius/gitget/global/security/handler/OAuth2SuccessHandler.java
  src/main/java/com/genius/gitget/global/security/service/JwtService.java
  src/main/java/com/genius/gitget/global/util/config/AppConfig.java
  src/main/resources/data.sql
  src/test/java/com/genius/gitget/global/security/service/JwtServiceTest.java
Labels: 🧑🏻‍💻 BE, 🖥️ server

#160 [FIX] 파일 저장 시, 특정 용량 이상의 파일이 전달되었을 때 발생하는 예외 추가 처리
  src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
  src/main/java/com/genius/gitget/global/util/exception/FileExceptionHandler.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 !HOTFIX

#163 [BUILD] Nginx를 활용한 무중단 배포
  .github/workflows/main.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  scripts/health.sh
  scripts/run_new_was.sh
  scripts/start.sh
  scripts/stop.sh
  scripts/switch.sh
  src/main/java/com/genius/gitget/GitgetApplication.java
Labels: 💡feature, 🧑🏻‍💻 BE, 🖥️ server

#166 [FEAT] AWS S3 이미지 관련 기능 개발
  .github/workflows/test-task.yml
  build.gradle
  src/main/java/com/genius/gitget/global/file/service/FileUtil.java
  src/main/java/com/genius/gitget/global/file/service/S3FileManager.java
  src/main/java/com/genius/gitget/global/util/config/AppConfig.java
  src/main/java/com/genius/gitget/global/util/config/S3Config.java
  src/test/java/com/genius/gitget/challenge/instance/controller/InstanceControllerTest.java
  src/test/java/com/genius/gitget/challenge/likes/controller/LikesControllerTest.java
  src/test/java/com/genius/gitget/profile/controller/ProfileControllerTest.java
Labels: 💡feature, 🧑🏻‍💻 BE, 🖥️ server

#171 [FEAT] main 브랜치에 PR 요청 시, 테스트 자동화 워크플로우 적용
  .github/workflows/prTest.yml
Labels: 🧑🏻‍💻 BE, 🖥️ server

#172 [FIX] 인스턴스 검색 결과에 인스턴스의 파일 정보가 넘어오지 않는 버그 픽스
  src/main/java/com/genius/gitget/challenge/instance/dto/search/InstanceSearchResponse.java
  src/main/java/com/genius/gitget/challenge/instance/repository/SearchRepositoryCustom.java
  src/main/java/com/genius/gitget/challenge/instance/repository/SearchRepositoryImpl.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceSearchService.java
  src/test/java/com/genius/gitget/challenge/instance/repository/InstanceSearchRepositoryTest.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 !HOTFIX

#169 [BUG] 좋아요 목록 조회 시 발생하는 버그 수정
  build.gradle
  src/main/java/com/genius/gitget/challenge/likes/service/LikesService.java
  src/test/java/com/genius/gitget/challenge/likes/service/LikesServiceTest.java
Labels: ⛔️ bug, 🧑🏻‍💻 BE, 🔧 !HOTFIX
