Repository TeamTheGenius/GitGet_Server, pull requests merged in 2024-01, with the labels that each got.

#16 Feat: 회원가입 API 개발
  build.gradle
  src/main/java/com/genius/todoffin/TodoffinApplication.java
  src/main/java/com/genius/todoffin/security/config/SecurityConfig.java
  src/main/java/com/genius/todoffin/security/domain/UserPrincipal.java
  src/main/java/com/genius/todoffin/security/handler/OAuth2FailureHandler.java
  src/main/java/com/genius/todoffin/security/handler/OAuth2SuccessHandler.java
  src/main/java/com/genius/todoffin/security/service/CustomOAuth2UserService.java
  src/main/java/com/genius/todoffin/user/controller/UserController.java
  src/main/java/com/genius/todoffin/user/domain/Role.java
  src/main/java/com/genius/todoffin/user/domain/User.java
  src/main/java/com/genius/todoffin/user/dto/SignupRequest.java
  src/main/java/com/genius/todoffin/user/repository/UserRepository.java
  src/main/java/com/genius/todoffin/user/service/UserService.java
  src/main/java/com/genius/todoffin/util/config/AppConfig.java
  src/main/java/com/genius/todoffin/util/config/SwaggerConfig.java
  src/main/java/com/genius/todoffin/util/exception/BusinessException.java
  src/main/java/com/genius/todoffin/util/exception/BusinessExceptionHandler.java
  src/main/java/com/genius/todoffin/util/exception/ErrorCode.java
  src/main/java/com/genius/todoffin/util/exception/GlobalExceptionHandler.java
  src/main/java/com/genius/todoffin/util/exception/SuccessCode.java
  src/main/java/com/genius/todoffin/util/formatter/CommonPattern.java
  src/main/java/com/genius/todoffin/util/formatter/LocalDateFormatter.java
  src/main/java/com/genius/todoffin/util/formatter/LocalDateTimeFormatter.java
  src/main/java/com/genius/todoffin/util/response/dto/CommonResponse.java
  src/main/java/com/genius/todoffin/util/response/dto/ListResponse.java
  src/main/java/com/genius/todoffin/util/response/dto/PagingResponse.java
  src/main/java/com/genius/todoffin/util/response/dto/SingleResponse.java
  src/main/java/com/genius/todoffin/util/response/dto/SlicingResponse.java
  src/test/java/com/genius/todoffin/user/repository/UserRepositoryTest.java
  src/test/java/com/genius/todoffin/user/service/UserServiceTest.java
Labels: enhancement, BE

#28 [FEAT] DB Entity 개발
  src/main/java/com/genius/todoffin/challenge/domain/Hits.java
  src/main/java/com/genius/todoffin/challenge/domain/Instance.java
  src/main/java/com/genius/todoffin/challenge/domain/JoinResult.java
  src/main/java/com/genius/todoffin/challenge/domain/ParticipantInfo.java
  src/main/java/com/genius/todoffin/challenge/domain/Progress.java
  src/main/java/com/genius/todoffin/challenge/domain/Topic.java
  src/main/java/com/genius/todoffin/challenge/repository/HitsRepository.java
  src/main/java/com/genius/todoffin/challenge/repository/InstanceRepository.java
  src/main/java/com/genius/todoffin/challenge/repository/TopicRepository.java
  src/main/java/com/genius/todoffin/common/domain/BaseTimeEntity.java
  src/main/java/com/genius/todoffin/security/constants/ProviderType.java
  src/main/java/com/genius/todoffin/security/domain/UserPrincipal.java
  src/main/java/com/genius/todoffin/security/handler/OAuth2SuccessHandler.java
  src/main/java/com/genius/todoffin/security/info/OAuth2UserInfoFactory.java
  src/main/java/com/genius/todoffin/security/info/impl/FacebookOAuth2UserInfo.java
  src/main/java/com/genius/todoffin/security/service/CustomOAuth2UserService.java
  src/main/java/com/genius/todoffin/user/domain/User.java
  src/main/java/com/genius/todoffin/user/dto/SignupRequest.java
  src/main/java/com/genius/todoffin/user/repository/UserRepository.java
  src/main/java/com/genius/todoffin/user/service/UserService.java
  src/test/java/com/genius/todoffin/user/repository/UserRepositoryTest.java
  src/test/java/com/genius/todoffin/user/service/UserServiceTest.java
Labels: enhancement, BE

#32 [REFACTOR] DB entity 리펙토링
  build.gradle
  src/main/java/com/genius/gitget/challenge/domain/Hits.java
  src/main/java/com/genius/gitget/challenge/domain/JoinResult.java
  src/main/java/com/genius/gitget/challenge/domain/ParticipantInfo.java
  src/main/java/com/genius/gitget/common/domain/BaseTimeEntity.java
  src/main/java/com/genius/gitget/hits/domain/Hits.java
  src/main/java/com/genius/gitget/hits/repository/HitsRepository.java
  src/main/java/com/genius/gitget/instance/domain/Instance.java
  src/main/java/com/genius/gitget/instance/domain/Progress.java
  src/main/java/com/genius/gitget/instance/repository/InstanceRepository.java
  src/main/java/com/genius/gitget/participantinfo/domain/JoinResult.java
  src/main/java/com/genius/gitget/participantinfo/domain/JoinStatus.java
  src/main/java/com/genius/gitget/participantinfo/domain/ParticipantInfo.java
  src/main/java/com/genius/gitget/participantinfo/repository/ParticipantInfoRepository.java
  src/main/java/com/genius/gitget/topic/domain/Topic.java
  src/main/java/com/genius/gitget/topic/repository/TopicRepository.java
  src/main/java/com/genius/gitget/user/domain/User.java
  src/test/java/com/genius/gitget/hits/HitsTest.java
  src/test/java/com/genius/gitget/instance/InstanceRepositoryTest.java
  src/test/java/com/genius/gitget/participantInfo/ParticipantInfoRepositoryTest.java
  src/test/java/com/genius/gitget/topic/TopicRepositoryTest.java
  src/test/java/com/genius/gitget/user/domain/UserTest.java
  src/test/java/com/genius/gitget/user/repository/UserRepositoryTest.java
Labels: enhancement, BE

#35 [FEAT] Controller(API) 테스트 코드 작성에 필요한 유틸 개발
  src/main/java/com/genius/gitget/security/controller/AuthController.java
  src/test/java/com/genius/gitget/security/controller/AuthControllerTest.java
  src/test/java/com/genius/gitget/util/TokenTestUtil.java
  src/test/java/com/genius/gitget/util/WithMockCustomUser.java
  src/test/java/com/genius/gitget/util/WithMockCustomUserSecurityContextFactory.java
Labels: enhancement, BE

#33 [FEAT] Admin 페이지 Instance , Topic API 개발
  src/main/java/com/genius/gitget/hits/domain/Hits.java
  src/main/java/com/genius/gitget/instance/controller/InstanceController.java
  src/main/java/com/genius/gitget/instance/domain/Instance.java
  src/main/java/com/genius/gitget/instance/dto/InstanceCreateRequest.java
  src/main/java/com/genius/gitget/instance/dto/InstanceDetailResponse.java
  src/main/java/com/genius/gitget/instance/dto/InstancePagingResponse.java
  src/main/java/com/genius/gitget/instance/dto/InstanceUpdateRequest.java
  src/main/java/com/genius/gitget/instance/repository/InstanceRepository.java
  src/main/java/com/genius/gitget/instance/service/InstanceService.java
  src/main/java/com/genius/gitget/participantinfo/domain/ParticipantInfo.java
  src/main/java/com/genius/gitget/security/config/SecurityConfig.java
  src/main/java/com/genius/gitget/topic/controller/TopicController.java
  src/main/java/com/genius/gitget/topic/domain/Topic.java
  src/main/java/com/genius/gitget/topic/dto/TopicCreateRequest.java
  src/main/java/com/genius/gitget/topic/dto/TopicDetailResponse.java
  src/main/java/com/genius/gitget/topic/dto/TopicPagingResponse.java
  src/main/java/com/genius/gitget/topic/dto/TopicUpdateRequest.java
  src/main/java/com/genius/gitget/topic/repository/TopicRepository.java
  src/main/java/com/genius/gitget/topic/service/TopicService.java
  src/main/java/com/genius/gitget/util/exception/ErrorCode.java
  src/main/java/com/genius/gitget/util/response/dto/PagingResponse.java
  src/test/java/com/genius/gitget/GitgetApplicationTests.java
  src/test/java/com/genius/gitget/hits/HitsTest.java
  src/test/java/com/genius/gitget/instance/InstanceRepositoryTest.java
  src/test/java/com/genius/gitget/mock/MockTest.java
  src/test/java/com/genius/gitget/participantInfo/ParticipantInfoRepositoryTest.java
  src/test/java/com/genius/gitget/topic/TopicControllerTest.java
  src/test/java/com/genius/gitget/topic/TopicRepositoryTest.java
Labels: enhancement, BE

#38 [FEAT] 어드민 페이지 개발
  src/main/java/com/genius/gitget/hits/domain/Hits.java
  src/main/java/com/genius/gitget/instance/controller/InstanceController.java
  src/main/java/com/genius/gitget/instance/domain/Instance.java
  src/main/java/com/genius/gitget/instance/dto/InstanceCreateRequest.java
  src/main/java/com/genius/gitget/instance/dto/InstanceDetailResponse.java
  src/main/java/com/genius/gitget/instance/dto/InstancePagingResponse.java
  src/main/java/com/genius/gitget/instance/dto/InstanceUpdateRequest.java
  src/main/java/com/genius/gitget/instance/repository/InstanceRepository.java
  src/main/java/com/genius/gitget/instance/service/InstanceService.java
  src/main/java/com/genius/gitget/participantinfo/domain/ParticipantInfo.java
  src/main/java/com/genius/gitget/security/config/SecurityConfig.java
  src/main/java/com/genius/gitget/topic/controller/TopicController.java
  src/main/java/com/genius/gitget/topic/domain/Topic.java
  src/main/java/com/genius/gitget/topic/dto/TopicCreateRequest.java
  src/main/java/com/genius/gitget/topic/dto/TopicDetailResponse.java
  src/main/java/com/genius/gitget/topic/dto/TopicPagingResponse.java
  src/main/java/com/genius/gitget/topic/dto/TopicUpdateRequest.java
  src/main/java/com/genius/gitget/topic/repository/TopicRepository.java
  src/main/java/com/genius/gitget/topic/service/TopicService.java
  src/main/java/com/genius/gitget/util/exception/ErrorCode.java
  src/main/java/com/genius/gitget/util/response/dto/PagingResponse.java
  src/test/java/com/genius/gitget/GitgetApplicationTests.java
  src/test/java/com/genius/gitget/hits/HitsTest.java
  src/test/java/com/genius/gitget/instance/InstanceRepositoryTest.java
  src/test/java/com/genius/gitget/mock/MockTest.java
  src/test/java/com/genius/gitget/participantInfo/ParticipantInfoRepositoryTest.java
  src/test/java/com/genius/gitget/topic/TopicControllerTest.java
  src/test/java/com/genius/gitget/topic/TopicRepositoryTest.java
Labels: enhancement, BE

#39 [FEAT] 이미지/파일 업로드 유틸 클래스 개발
  src/main/java/com/genius/gitget/file/controller/FilesController.java
  src/main/java/com/genius/gitget/file/domain/FileType.java
  src/main/java/com/genius/gitget/file/domain/Files.java
  src/main/java/com/genius/gitget/file/dto/FileResponse.java
  src/main/java/com/genius/gitget/file/dto/UploadDTO.java
  src/main/java/com/genius/gitget/file/repository/FilesRepository.java
  src/main/java/com/genius/gitget/file/service/FileUtil.java
  src/main/java/com/genius/gitget/file/service/FilesService.java
  src/main/java/com/genius/gitget/instance/domain/Instance.java
  src/main/java/com/genius/gitget/topic/domain/Topic.java
  src/main/java/com/genius/gitget/topic/service/TopicService.java
  src/main/java/com/genius/gitget/user/domain/User.java
  src/main/java/com/genius/gitget/util/exception/ErrorCode.java
  src/test/java/com/genius/gitget/file/repository/FilesRepositoryTest.java
  src/test/java/com/genius/gitget/file/service/FileUtilTest.java
  src/test/java/com/genius/gitget/file/service/FilesServiceTest.java
Labels: enhancement, BE

#45 [FIX] JWT 재발급 관련 버그 픽스
  src/main/java/com/genius/gitget/GitgetApplication.java
  src/main/java/com/genius/gitget/security/config/SecurityConfig.java
  src/main/java/com/genius/gitget/security/controller/AuthController.java
  src/main/java/com/genius/gitget/security/service/JwtService.java
  src/main/java/com/genius/gitget/security/service/JwtUtil.java
  src/main/java/com/genius/gitget/user/domain/User.java
  src/main/java/com/genius/gitget/util/exception/ErrorCode.java
  src/test/java/com/genius/gitget/file/service/FileUtilTest.java
  src/test/java/com/genius/gitget/file/service/FilesServiceTest.java
  src/test/java/com/genius/gitget/hits/HitsTest.java
  src/test/java/com/genius/gitget/security/service/JwtServiceTest.java
  src/test/java/com/genius/gitget/topic/TopicControllerTest.java
  src/test/java/com/genius/gitget/user/repository/UserRepositoryTest.java
Labels: ⛔️ bug, 🔧 !HOTFIX

#47 [TEST] JWT, 회원가입 로직 테스트 코드 추가
  src/main/java/com/genius/gitget/security/service/JwtService.java
  src/test/java/com/genius/gitget/security/service/JwtServiceTest.java
  src/test/java/com/genius/gitget/security/service/JwtUtilTest.java
  src/test/java/com/genius/gitget/user/controller/UserControllerTest.java
  src/test/java/com/genius/gitget/user/service/UserServiceTest.java
  src/test/java/com/genius/gitget/util/TokenTestUtil.java
Labels: 🧑🏻‍💻 BE, 🎮 test

#49 [REFACTOR] 이미지/파일 요청과 응답 시 base64 인코딩하여 전달하도록 변경
  src/main/java/com/genius/gitget/global/file/controller/FilesController.java
  src/main/java/com/genius/gitget/global/file/dto/FileRequest.java
  src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
  src/main/java/com/genius/gitget/global/file/service/FileUtil.java
  src/main/java/com/genius/gitget/global/file/service/FilesService.java
Labels: ⚙️ refactor, 🧑🏻‍💻 BE

#51 [FEAT] 홈 화면 - 챌린지 검색 기능 개발
  build.gradle
  src/main/java/com/genius/gitget/admin/topic/domain/Topic.java
  src/main/java/com/genius/gitget/admin/topic/service/TopicService.java
  src/main/java/com/genius/gitget/challenge/instance/config/WebConfig.java
  src/main/java/com/genius/gitget/challenge/instance/controller/HomeController.java
  src/main/java/com/genius/gitget/challenge/instance/controller/InstanceController.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Progress.java
  src/main/java/com/genius/gitget/challenge/instance/domain/StringToEnum.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceCreateRequest.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceDetailResponse.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstancePagingResponse.java
  src/main/java/com/genius/gitget/challenge/instance/dto/crud/InstanceUpdateRequest.java
  src/main/java/com/genius/gitget/challenge/instance/dto/search/InstanceSearchRequest.java
  src/main/java/com/genius/gitget/challenge/instance/dto/search/InstanceSearchResponse.java
  src/main/java/com/genius/gitget/challenge/instance/repository/InstanceRepository.java
  src/main/java/com/genius/gitget/challenge/instance/repository/SearchRepository.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceSearchService.java
  src/main/java/com/genius/gitget/challenge/instance/service/InstanceService.java
  src/main/java/com/genius/gitget/challenge/participantinfo/domain/ParticipantInfo.java
  src/main/java/com/genius/gitget/global/file/controller/FilesController.java
  src/main/java/com/genius/gitget/global/security/repository/TokenRepository.java
  src/test/java/com/genius/gitget/file/service/FilesServiceTest.java
  src/test/java/com/genius/gitget/hits/HitsTest.java
  src/test/java/com/genius/gitget/instance/InstanceControllerTest.java
  src/test/java/com/genius/gitget/instance/InstanceRepositoryTest.java
  src/test/java/com/genius/gitget/instance/InstanceSearchRepositoryTest.java
  src/test/java/com/genius/gitget/instance/InstanceSearchServiceTest.java
  src/test/java/com/genius/gitget/instance/InstanceServiceTest.java
  src/test/java/com/genius/gitget/topic/TopicControllerTest.java
  src/test/java/com/genius/gitget/topic/TopicRepositoryTest.java
  src/test/java/com/genius/gitget/topic/TopicServiceTest.java
Labels: 💡feature, ⚙️ refactor, 🧑🏻‍💻 BE, 🎮 test

#50 [FEAT] 홈 화면 - 추천/인기/신규 기능 개발
  src/main/java/com/genius/gitget/challenge/home/controller/HomeController.java
  src/main/java/com/genius/gitget/challenge/home/dto/HomeInstanceResponse.java
  src/main/java/com/genius/gitget/challenge/home/service/HomeService.java
  src/main/java/com/genius/gitget/challenge/instance/domain/Instance.java
  src/main/java/com/genius/gitget/challenge/instance/repository/InstanceRepository.java
  src/main/java/com/genius/gitget/challenge/user/domain/User.java
  src/main/java/com/genius/gitget/global/file/controller/FilesController.java
  src/main/java/com/genius/gitget/global/file/domain/Files.java
  src/main/java/com/genius/gitget/global/file/dto/FileResponse.java
  src/main/java/com/genius/gitget/global/file/dto/UpdateDTO.java
  src/main/java/com/genius/gitget/global/file/service/FileUtil.java
  src/main/java/com/genius/gitget/global/file/service/FilesService.java
  src/main/java/com/genius/gitget/global/util/exception/ErrorCode.java
  src/main/java/com/genius/gitget/global/util/response/dto/SlicingResponse.java
  src/test/java/com/genius/gitget/challenge/home/controller/HomeControllerTest.java
  src/test/java/com/genius/gitget/challenge/home/service/HomeServiceTest.java
  src/test/java/com/genius/gitget/challenge/instance/repository/InstanceRepositoryTest.java
  src/test/java/com/genius/gitget/file/service/FileUtilTest.java
  src/test/java/com/genius/gitget/global/file/domain/FilesTest.java
  src/test/java/com/genius/gitget/hits/HitsTest.java
  src/test/java/com/genius/gitget/security/service/JwtServiceTest.java
  src/test/java/com/genius/gitget/topic/TopicControllerTest.java
  src/test/java/com/genius/gitget/user/controller/UserControllerTest.java
  src/test/java/com/genius/gitget/user/domain/UserTest.java
  src/test/java/com/genius/gitget/user/service/UserServiceTest.java
Labels: 💡feature, ⚙️ refactor, 🧑🏻‍💻 BE
